server:
  port: '8082'

spring:
  profiles:
    active: qa
---

spring:
  datasource:
    profiles: dev
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Daily Code Buffer!!

---
spring:
  datasource:
    profiles: qa
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Daily Code Buffer!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

  spring:
    datasource:
      profiles: prod
      username: root
      url: jdbc:mysql://localhost:3306/dcbapp-pro
      password: password
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: 'true'
  welcome:
    message: Welcome to Daily Code Buffer!!